### ISSUE TITLE
Possible to make a dutch version 

### ISSUE THREAD

**Issue by ThnksCJ** [mcnaveen/Random-Words-API#45]
would it be possible to make a dutch version were it takes the info from https://www.generatormix.com/random-dutch-words-generator

and outputs the dutch instead of the word and the english instead of the meaning?

**Comment by mcnaveen** [comment]
Random Dutch Words is now live

API Endpoint is `/word/dutch`

:rocket: Demo is available at:  **https://random-words-api.vercel.app/word/dutch**
