### ISSUE TITLE
less of an an issue, more of a query

### ISSUE THREAD

**Issue by dev-shah-2204** [mcnaveen/Random-Words-API#48]
Is there a way for me to get a word of some specific length? Say, I pass "5" as an argument and I receive a 5 letter word. 

Now, I could check for the length of the word in the response and re-call the API if the length of the word is not equal to the length I want, but that would slow down both, the process and the API, right?

**Comment by mcnaveen** [comment]
Unfortunately, there is no way we can do that right now. Maybe in the future, I'll try to implement it.

Thanks for your understanding

**Comment by dev-shah-2204** [comment]
Sure no worries, I ended up using a text file containing over 650 5-letter words

**Comment by mcnaveen** [comment]
Awesome.

I'm gonna close this issue. Please reopen if anything else is needed. 

Thanks.
