### ISSUE TITLE
Speak & Spell usage of the API :)

### ISSUE THREAD

**Issue by gacallea** [mcnaveen/Random-Words-API#68]
Hi @mcnaveen :)

I wanted to thank you for the API and let you know that I've used your API for my Elm learning project. Up to you if you want to include it in the README as example usage.

game: https://speak-and-spell.vercel.app/
code: https://github.com/gacallea/elm_speakandspell

Cheers!

**Comment by mcnaveen** [comment]
Hi @gacallea 

Thank you so much for using this API to build your project. Good to see so many people are using this 🎉 

Note: I hope the pending PR #67 will give more flexibility for words to your application. Will try to merge it asap.

**Comment by gacallea** [comment]
Hi @mcnaveen!

PR67 seems very interesting. For Speak & Spell may be too much. Are you going to leave a default behavior as is now? (Or perhaps I could randomize the category endpoint to get a different kind of words every time?).

One feature I really like is the availability for different languages. If that is going to include more languages, I've always "dreamt" of adding the possibility of [language, gender, voice, customizations](https://github.com/gacallea/elm_speakandspell/blob/main/TODO.md#maybe=). 

Anyway, Speak & Spell is complete (for now). Additions would be nice, but not necessary at this point. I'll keep an eye on the API, as it may inspire me to do some more work on it. :)

Tthank you so much for this great project and for the kind words!

Cheers

**Comment by mcnaveen** [comment]
PR #67 Introduced a new bug. Dutch API Endpoint isn't working. Because of route conflicts.
Nothing is going to change and I'll improve on language side based on the user requirements.

Thanks again. 🙏

**Comment by mcnaveen** [comment]
@gacallea Dutch Endpoint issue got fixed. Thanks to @mskian for his efforts.

I'm planning to add more languages. Do you have any suggestions in mind?

**Comment by gacallea** [comment]
> I'm planning to add more languages. Do you have any suggestions in mind?

Not sure how easy it is to add a language, and from where you get your dictionary/thesaurus. That being said, if this was my API, I'd have the most spoken (Latin alphabet) European languages: English, French, German, Spanish, Italian, Portuguese.

Cheers :)

**Comment by mcnaveen** [comment]
> Not sure how easy it is to add a language, and from where you get your dictionary/thesaurus

Well, It's quite a time taking work, but it's worth it. I have a scrapper hooked with Prisma/SQLite. Once I'm done with scrapping I'll add it inside the `data` folder. Just like I did for dutch.

**Comment by gacallea** [comment]
hi @mcnaveen :)

speak and spell is now also in Dutch :)

https://speak-and-spell.vercel.app/

ps: please forgive the google translate for the interface!

**Comment by mcnaveen** [comment]
That's cool. 🥺❤️

Haha, Even myself don't know Dutch. 

I'll include this in README soon. Lazy af 😩

**Comment by mcnaveen** [comment]
> Up to you if you want to include it in the README as example usage.

Finally: https://github.com/mcnaveen/Random-Words-API#-used-by
