### ISSUE TITLE
Dutch API Endpoint returns error

### ISSUE THREAD

**Issue by mcnaveen** [mcnaveen/Random-Words-API#69]
Merging PR #67 Introduced a route conflict for Dutch API endpoint and returns "Something Went Wrong - Enter the Correct API URL"

Current route
`https://random-words-api.vercel.app/word`

Expected route
`https://random-words-api.vercel.app/dutch`

If you can work on this issue. Please do and send a PR.

**Comment by mskian** [comment]
will check this weekend 
planning to rewrite API validation

**Comment by mcnaveen** [comment]
Awesome, Looking forward to it. 😄
